///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : controldata.cpp
/// SOFTWARE COMPONENT NAME           : ControlData
/// GENERATED DATE                    : 2024-08-14 09:44:02
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "calc/aa/port/controldata.h"
 
namespace deepracer
{
namespace service
{
namespace controldata
{
namespace skeleton
{

// SvControlData Service Interface에 대한 Skeleton Impl 클래스 생성자
SvControlDataSkeletonImpl::SvControlDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvControlDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("CALC", "PORT", ara::log::LogLevel::kVerbose))
{
}

// SvControlData는 Event만 존재하기 때문에 SvControlDataSkeletonImpl의 구현부는 더 이상 Code Generate가 되지 않았다.
 
} /// namespace skeleton
} /// namespace controldata
} /// namespace service
} /// namespace deepracer

namespace calc
{
namespace aa
{
namespace port
{

// ControlData PPort Interface에 대한 생성자
ControlData::ControlData()
    : m_logger(ara::log::CreateLogger("CALC", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_CEventData{0U}
{
}
 
ControlData::~ControlData()
{
}

// PPort ControlData의 시작 함수.
// 해당 Port는 PPort이므로 서비스에 대한 OfferService를 호출하게 된다.
void ControlData::Start()
{
    m_logger.LogVerbose() << "ControlData::Start";

    // Skeleton 생성
    ara::core::InstanceSpecifier specifier{"Calc/AA/ControlData"};
    m_interface = std::make_shared<deepracer::service::controldata::skeleton::SvControlDataSkeletonImpl>(specifier);

    // Skeleton을 통해 Offer Service 호출
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "ControlData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "ControlData::Start::OfferService::" << offer.Error().Message();
    }
}

// Port의 종료 처리 함수
void ControlData::Terminate()
{
    m_logger.LogVerbose() << "ControlData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "ControlData::Terminate::StopOfferService";
}

// 현재 CEvent 데이터를 갱신하는 함수
void ControlData::WriteDataCEvent(const deepracer::service::controldata::skeleton::events::CEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_CEventData = data;
}

// CEvent 데이터를 주기적으로 보내는 함수.
// 현재 포트가 보유한 m_CEventData 기준으로 데이터를 전송
void ControlData::SendEventCEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->CEvent.Send(m_CEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "ControlData::SendEventCEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "ControlData::SendEventCEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}

// CEvent 데이터를 트리거 형태로 보내는 함수.
// 현재 포트가 보유한 m_CEventData 기준으로 데이터를 전송
void ControlData::SendEventCEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->CEvent.Send(m_CEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "ControlData::SendEventCEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "ControlData::SendEventCEventTriggered::Send::" << send.Error().Message();
    }
}

// CEvent 데이터를 트리거 형태로 보내는 함수.
// 해당 함수의 argument를 데이터를 전송
void ControlData::SendEventCEventTriggered(const deepracer::service::controldata::skeleton::events::CEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_CEventData = data;
    auto send = m_interface->CEvent.Send(m_CEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "ControlData::SendEventCEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "ControlData::SendEventCEventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace calc
 
/// EOF