///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rawdata.cpp
/// SOFTWARE COMPONENT NAME           : RawData
/// GENERATED DATE                    : 2024-08-14 09:44:02
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/rawdata.h"
 
namespace deepracer
{
namespace service
{
namespace rawdata
{
namespace skeleton
{

// SvRawData Service Interface에 대한 Skeleton Impl 클래스 생성자
SvRawDataSkeletonImpl::SvRawDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvRawDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
    , m_RField{0U}
{
    // RField에 대한 get 핸들러 등록
    auto rfield_get_handler = [this]() {
        return GetRField();
    };
    RField.RegisterGetHandler(rfield_get_handler);

    // RField에 대한 set 핸들러 등록
    auto rfield_set_handler = [this](const fields::RField::FieldType& value) {
        return SetRField(value);
    };
    RField.RegisterSetHandler(rfield_set_handler);
}

// RMethod에 대한 override 함수.
// 해당 함수에서 RField에 대하여 구현해주어야 한다.
ara::core::Future<SvRawDataSkeleton::RMethodOutput> SvRawDataSkeletonImpl::RMethod(const double& a, const deepracer::type::Arithmetic& arithmetic, const double& b)
{
    m_logger.LogVerbose() << "RawData::RMethod::Requested";
    
    RMethodOutput response;
    ara::core::Promise<RMethodOutput> promise;

    // 기본 Generate 코드에서는 해당 구현부분이 정의되지 않으며, 개발자가 직접 RMethod에 대한 처리를 구현해 주어야 한다.
    switch (arithmetic)
    {
        case type::Arithmetic::kAdd:
            m_logger.LogInfo() << "RawData::RMethod " << a << " Add " << b;
            response.result = a + b;
            break;
        case type::Arithmetic::kSub:
            m_logger.LogInfo() << "RawData::RMethod " << a << " Sub " << b;
            response.result = a - b;
            break;
        case type::Arithmetic::kMul:
            m_logger.LogInfo() << "RawData::RMethod " << a << " Mul " << b;
            response.result = a * b;
            break;
        case type::Arithmetic::kDiv:
            m_logger.LogInfo() << "RawData::RMethod " << a << " Div " << b;
            if (b == 0.0)
            {
                response.result = 0.0;
            }
            else
            {
                response.result = a / b;
            }
            break;
        default:
            response.result = 0.0;
            break;
    }
    
    promise.set_value(response);
    return promise.get_future();
}

// RField에 대한 Getter 처리 함수
ara::core::Future<fields::RField::FieldType> SvRawDataSkeletonImpl::GetRField()
{
    m_logger.LogVerbose() << "RawData::GetRField::Requested";
    
    ara::core::Promise<fields::RField::FieldType> promise;
    
    promise.set_value(m_RField);
    return promise.get_future();
}

// RField에 대한 Setter 처리 함수
ara::core::Future<fields::RField::FieldType> SvRawDataSkeletonImpl::SetRField(const fields::RField::FieldType& value)
{
    m_logger.LogVerbose() << "RawData::SetRField::Requested";
    
    ara::core::Promise<fields::RField::FieldType> promise;
    
    // set field value
    m_RField = value;
    
    promise.set_value(m_RField);
    return promise.get_future();
}

// RField에 대한 Notify 처리 함수
void SvRawDataSkeletonImpl::NotifyRField()
{
    auto notify = RField.Update(m_RField);
    if (notify.HasValue())
    {
        m_logger.LogVerbose() << "RawData::NotifyRField::Update";
    }
    else
    {
        m_logger.LogError() << "RawData::NotifyRField::Update::" << notify.Error().Message();
    }
}

// RField에 대한 값 변경 함수.
void SvRawDataSkeletonImpl::UpdateRField(const fields::RField::FieldType& value)
{
    m_RField = value;
}
 
} /// namespace skeleton
} /// namespace rawdata
} /// namespace service
} /// namespace deepracer

namespace sensor
{
namespace aa
{
namespace port
{

// RawData PPort Interface에 대한 생성자
RawData::RawData()
    : m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_REventData{0U}
{
}
 
RawData::~RawData()
{
}

// PPort RawData의 시작 함수.
// 해당 Port는 PPort이므로 서비스에 대한 OfferService를 호출하게 된다.
void RawData::Start()
{
    m_logger.LogVerbose() << "RawData::Start";
    
    // Skeleton 생성
    ara::core::InstanceSpecifier specifier{"Sensor/AA/RawData"};
    m_interface = std::make_shared<deepracer::service::rawdata::skeleton::SvRawDataSkeletonImpl>(specifier);
    
    // Skeleton을 통해 Offer Service 호출
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "RawData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "RawData::Start::OfferService::" << offer.Error().Message();
    }
}

// Port의 종료 처리 함수
void RawData::Terminate()
{
    m_logger.LogVerbose() << "RawData::Terminate";
    
    // Port 처리를 멈춘다.
    m_running = false;

    // Skeleton을 통해 Stop Offer Service 호출.
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "RawData::Terminate::StopOfferService";
}

// 현재 REvent 데이터를 갱신하는 함수
void RawData::WriteDataREvent(const deepracer::service::rawdata::skeleton::events::REvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_REventData = data;
}

// REvent 데이터를 주기적으로 보내는 함수.
// 현재 포트가 보유한 m_REventData 기준으로 데이터를 전송
void RawData::SendEventREventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            // Skeleton을 통해 REvent 값을 전송
            auto send = m_interface->REvent.Send(m_REventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "RawData::SendEventREventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "RawData::SendEventREventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}

// REvent 데이터를 트리거 형태로 보내는 함수.
// 현재 포트가 보유한 m_REventData 기준으로 데이터를 전송
void RawData::SendEventREventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->REvent.Send(m_REventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "RawData::SendEventREventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "RawData::SendEventREventTriggered::Send::" << send.Error().Message();
    }
}

// REvent 데이터를 트리거 형태로 보내는 함수.
// 해당 함수의 argument를 데이터를 전송
void RawData::SendEventREventTriggered(const deepracer::service::rawdata::skeleton::events::REvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_REventData = data;
    auto send = m_interface->REvent.Send(m_REventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "RawData::SendEventREventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "RawData::SendEventREventTriggered::Send::" << send.Error().Message();
    }
}

// RField에 대한 데이터 변경 함수
void RawData::WriteValueRField(const deepracer::service::rawdata::skeleton::fields::RField::FieldType& value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_interface->UpdateRField(value);
}

// RField 데이터를 주기적으로 Notify하는 함수
void RawData::NotifyFieldRFieldCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            m_interface->NotifyRField();
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}

// RField 데이터를 트리거 형태로 Notify하는 함수.
void RawData::NotifyFieldRFieldTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_interface->NotifyRField();
}

// RField 데이터를 트리거 형태로 Notify하는 함수.
// Skeleton 내의 RField 값을 변경 한 후 Notify한다.
void RawData::NotifyFieldRFieldTriggered(const deepracer::service::rawdata::skeleton::fields::RField::FieldType& value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_interface->UpdateRField(value);
    m_interface->NotifyRField();
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensor
 
/// EOF